
== Criando um aplicativo com Hibernate

No mundo relacional exitem diversos frameworks ORM do qual facilita a integração entre a aplicação e o objeto relacional, dentre eles, o mais famoso no mundo Java é o Hiberante. O Hibernate é um ORM Java open source criado por Gavin King e, atualmente, é desenvolvimento pela RedHat. Um ponto importante é que no mundo Java existe processo de padronização que é a JSR, Java Speficication Request, regido pelo JCP, Java Community Process. A especificação do mundo Java e o banco relacional é o JPA que faz parte da plataforma Java EE e o JPA foi insiprado pelo Hibernate. Assim como o Spring o Hibernate possui diversos subprojetos para facilitar o mundo de desenvolvimento mais focado no mundo de persistência de dados, por exemplo, Hibernate Search, Hibernate Validator, dentre outras coisas. Nesse capítulo, falemos um pouco mais sobre esse framework e sua relação com o mundo não relacional com o Hibernate OGM.

=== O que é Hibernate OGM?

Com o objetivo de facilitar a comunicação a curva de aprendizagem dos desenvolvedores para começar a aprender os bancos não relacionais, nasceu o Hibernate OGM. Sua abordagem é bastante simples, utilizar uma API relacional, que muitos desenvolvedores Java já conhecem para o mundo do banco não relacional, dentre os bancos que esse projeto tem suporte podemos citar:


* Cassandra
* CouchDB
* EhCache
* Apache Ignite
* Redis

Dentre as suas facilidades podemos citar a baixa curva de aprendizagem por parte do desenvolvedor uma vez que o desenvolvedor Java tende a conhecer o JPA, consultas em JPQL que são convertidas para query nativa em background, full-text queries utlizando Hibernate Search.


=== Exemplo prático com Hibernate OGM



Utilizar uma API que o desenvolvedor já conhece para navegar um novo paradigma no mundo da persistência é uma grande estratégia do qual o Hibernate tira o proveito dessa lacuna. Porém, essa facilidade cobre o seu preço uma vez que o JPA foi feito para o banco de dados relacional, assim, existem diversas lacunas que API tende a não cobrir no mundo NoSQL, por exemplo, operações de maneira assincronia assim como definições de nível de consistência existente no Cassandra.

